name: MMOItemsPerWorldDrops
version: ${project.version}
main: net.Indyuce.mmoitems.addon.WorldDrops
author: Indyuce
depend: [ MMOItems ]
description: ${project.description}
api-version: 1.13
commands:
  mmoitemsworlddrops:
    description: Reloads drop data.
permissions: { }